# Content_wise_Movie_Recommandation_Engine

In [97]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [98]:
data=pd.read_csv('movie_dataset_github.csv')
data.head(2)

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   

                                                crew        director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...   James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...  Gore Verbinski  

[2 rows x 24 columns]

In [99]:
data.drop(columns=['budget','homepage','original_language','runtime','spoken_languages','status'],inplace=True)

In [100]:
Movie_features = ['keywords','cast','genres','director','tagline']

In [101]:
data['title'].nunique()

4800

In [102]:
def combined_movie_features(row):
 return row['keywords']+" "+row['cast']+" "+row['genres']+" "+row['director']+" "+row['tagline']

In [103]:
for feature in Movie_features:
    data[feature] = data[feature].fillna('') 

In [104]:
data['combined_movie_features'] = df.apply(combined_movie_features,axis=1)

In [105]:
data.head(2)

index                                    genres     id  \
0      0  Action Adventure Fantasy Science Fiction  19995   
1      1                  Adventure Fantasy Action    285   

                                            keywords  \
0  culture clash future space war space colony so...   
1  ocean drug abuse exotic island east india trad...   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title  vote_average  vote_count  \
0                                    Avatar           7.2       11800   
1  Pirates of the Caribbean: At World's End           6.9        4500   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   

                                                crew        director  \
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...   James Cameron   
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...  Gore Verbinski   

                             combined_movie_features  
0  culture clash future space war space colony so...  
1  ocean drug abuse exotic island east india trad...

In [106]:
cvr = CountVectorizer()
count_matrix = cvr.fit_transform(df['combined_features'])

In [107]:
print(count_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [108]:
cosine_similarity = cosine_similarity(count_matrix)

In [109]:
print(cosine_similarity)

[[1.         0.25253814 0.10206207 ... 0.         0.         0.        ]
 [0.25253814 1.         0.10997148 ... 0.05714286 0.         0.        ]
 [0.10206207 0.10997148 1.         ... 0.         0.09072184 0.        ]
 ...
 [0.         0.05714286 0.         ... 1.         0.         0.04264014]
 [0.         0.         0.09072184 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.04264014 0.         1.        ]]


In [110]:
def get_title_from_index(index):
    return df[df['index'] == index]['title'].values[0]
def get_index_from_movie_title(title):
    return df[df['title'] == title ]['index'].values[0]

In [111]:
#check this Fumction:-
mask=df[df['title']=='Deadpool']
mask

index                   genres      id  \
788    788  Action Adventure Comedy  293660   

                                              keywords original_title  \
788  anti hero mercenary marvel comic superhero bas...       Deadpool   

                                              overview  popularity  \
788  Deadpool tells the origin story of former Spec...  514.569956   

                                  production_companies  \
788  [{"name": "Twentieth Century Fox Film Corporat...   

                                  production_countries release_date  \
788  [{"iso_3166_1": "US", "name": "United States o...   2016-02-09   

       revenue                                  tagline     title  \
788  783112979  Witness the beginning of a happy ending  Deadpool   

     vote_average  vote_count  \
788           7.4       10995   

                                                  cast  \
788  Ryan Reynolds Morena Baccarin Ed Skrein T.J. M...   

                                                  crew    director  \
788  [{'name': 'Ronna Kress', 'gender': 1, 'departm...  Tim Miller   

                                     combined_features  
788  anti hero mercenary marvel comic superhero bas...

In [140]:
movie_user_likes='Avatar'
movie_index = get_index_from_movie_title(movie_user_likes)
similar_movies=list(enumerate(cosine_sim[movie_index]))



In [141]:
#print(similar_movies)

In [142]:
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)[1:]

In [143]:
sorted_similar_movies[0]

(94, 0.36109269036423697)

In [144]:
i=0
print("Top 5 similar movies to "+ movie_user_likes)
for element in sorted_similar_movies:
    print(get_title_from_index(element[0]))
    i=i+1
    if i>5:
        break

Top 5 similar movies to Avatar
Guardians of the Galaxy
Aliens
Star Wars: Clone Wars: Volume 1
Alien
Star Trek Beyond
Star Trek Into Darkness
